// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBNaHMI2sQo5zAgPuUAZT_VOINodfimcV4',
    appId: '1:651738565362:web:4dbf980f9a46e2b86e1e6b',
    messagingSenderId: '651738565362',
    projectId: 'task-96da4',
    authDomain: 'task-96da4.firebaseapp.com',
    storageBucket: 'task-96da4.appspot.com',
    measurementId: 'G-7WYMHD26ND',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyArbRVK1jQK5wvolFTlYmgxeEJfoc2KemM',
    appId: '1:651738565362:android:77269240e77a40446e1e6b',
    messagingSenderId: '651738565362',
    projectId: 'task-96da4',
    storageBucket: 'task-96da4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD9yhJFbfotTHJzPBjd0sVNkTp9S7tMzPU',
    appId: '1:651738565362:ios:9321c606cdf798116e1e6b',
    messagingSenderId: '651738565362',
    projectId: 'task-96da4',
    storageBucket: 'task-96da4.appspot.com',
    iosBundleId: 'com.example.flutterFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD9yhJFbfotTHJzPBjd0sVNkTp9S7tMzPU',
    appId: '1:651738565362:ios:9321c606cdf798116e1e6b',
    messagingSenderId: '651738565362',
    projectId: 'task-96da4',
    storageBucket: 'task-96da4.appspot.com',
    iosBundleId: 'com.example.flutterFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBNaHMI2sQo5zAgPuUAZT_VOINodfimcV4',
    appId: '1:651738565362:web:dffdd15888b0ba5b6e1e6b',
    messagingSenderId: '651738565362',
    projectId: 'task-96da4',
    authDomain: 'task-96da4.firebaseapp.com',
    storageBucket: 'task-96da4.appspot.com',
    measurementId: 'G-D5S8J3WNX0',
  );
}
